apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialist-booking-webapi
  labels:
    wac-fiit.github.io/component: backend
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /specialist-booking-openapi
            - name: BASE_URL
              value: /specialist-booking-openapi-ui
