apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: tomdrg/specialist-booking-ufe
    newName: tomdrg/specialist-booking-ufe
    newTag: 1.0.9
  - name: tomdrg/specialist-booking-webapi
    newName: tomdrg/specialist-booking-webapi
    newTag: 1.0.6
