apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: specialist-booking-webapi
  namespace: wac-hospital
spec:
  imageRepositoryRef:
    name: specialist-booking-webapi
  filterTags:
    pattern: "main.*"
  policy:
    alphabetical:
      order: asc
